name:           TestingNGLESS
version:        '0.7.0'
category:       Domain Specific Language
author:         Luis Pedro Coelho and others (see AUTHORS)
maintainer:     luis@luispedro.org
github:         luispedro/ngless
license:        MIT
license-file:   COPYING
default-extensions:
  - BangPatterns
  - OverloadedStrings
  - LambdaCase
  - TupleSections
other-extensions:
  - DeriveDataTypeable
  - TemplateHaskell
dependencies:
  - base
  - bytestring
  - conduit
  - conduit-combinators
  - conduit-extra >=1.1.12
  - mtl >=2.2
  - resourcet >=1.1
  - transformers

when:
  - condition: impl(ghc >=8.0)
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -fno-warn-missing-signatures
      - -threaded
      - -O2
      - -rtsopts
      - ! '"-with-rtsopts=-A64m -n4m -H"'
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -fno-warn-missing-signatures
      - -threaded
      - -O2
      - -rtsopts
      - ! '"-with-rtsopts=-A64m -n4m -H -qg"'

executables:
  testingNGLESS:
    main: Main.hs
    source-dirs: Execs
    other-modules: []
    dependencies:
        - TestingNGLESS
library:
    source-dirs: NGLess/
